name: LFI Bug Bounty Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lfi-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests
          sudo apt-get update
          sudo apt-get install -y httpie

      - name: Run LFI Pipeline
        run: |
          chmod +x lfi_pipeline.sh
          ./lfi_pipeline.sh
